### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by maskedcoder** [inuitcss/getting-started#12]
@csswizardry hasn't done much on GitHub since last July besides merge 3 pull requests, and (as far as I can tell) he hasn't been responding to issues for several months.

[Several](https://github.com/inuitcss/objects.block/pulls) [of](https://github.com/inuitcss/objects.layout/pulls) [Inuitcss'](https://github.com/inuitcss/trumps.spacing/pulls) [repositories](https://github.com/inuitcss/objects.pack/pulls) have multiple open pull requests. There have been discussions about making major changes (such as adding namespaces and responsive suffixes), but not much has been done, even though there are open PRs by people wanting to implement them.

Is Inuitcss no longer being maintained? Should I start looking for a different framework to use in my future projects?

_(I'm not asking for suggestions of alternatives--just wanting to know what's going on with Inuit.)_

**Comment by edbentinck** [comment]
A far-from-ideal alternative could be to fork the repos and make those changes yourself. I for one would definitely be keen to use an updated version of Inuit :smile: .. just not enough to do all the forking myself! haha

**Comment by nenadjelovac** [comment]
@maskedcoder @edbentinck 

> Should I start looking for a different framework to use in my future projects?

To help you answer this question (a lot of people have it), could you please answer this question (for me):

What are the _blockers_ (if any) you're running into with current version of inuitcss?  

I would also _like_ to see an updated version of inuitcss as well (I am working on that). 
But for me inuitcss in this form (and it's still alpha) is levels ahead of any css framework out there. Yes, there are a few annoyances and small bugs, but nothing stopping me (ATM) from continuing using it.

Thanks!

P.S. there are workarounds (as @edbentinck suggested) if you really need to move something forward. There's even inuitcss fork called [Aleut.css](http://aleutcss.github.io/) (which is an opinionated version of inuit, so make sure to look at the differences).

cc @csswizardry @inuitcss/owners @csshugs

**Comment by maskedcoder** [comment]
First let me say something I should have mentioned first: I love Inuit. I think @csswizardry  has a lot of great ideas. I really appreciate that he and @anselmh  have taken the time to create it, and that you have taken the time to help with people's issues. I understand that you guys are not obligated to do anything like this, but still chose to spend a lot of time working on it.

Thank you very much. :+1:

### Background

For the last few months, I've been using a workaround of sorts. I copied most of Inuit directly into my projects and made various customizations, such as Harry's namespace prefixes and responsive suffixes (I don't remember what else).

For my newest project, I thought I would try using Inuit the way the readme files recommended.

### Blockers

So far, documentation is really the biggest blocker. Every time I want to use something, I have to look at the source again to see if I have the name right. It would be helpful if the readmes had a list of flags to begin with.

Another problem is the inconsistent namespaces. For example, normal spacing [has a `u-` namespace](https://github.com/inuitcss/trumps.spacing/blob/master/_trumps.spacing.scss#L61) by default (for which there is no option to change). Responsive spacing [does not](https://github.com/inuitcss/trumps.spacing-responsive/blob/master/_trumps.spacing-responsive.scss#L81). (By the way, the normal spacing's [readme](https://github.com/inuitcss/trumps.spacing/blob/master/README.md) has incorrect examples, without the `u-`.)

Both of those problems have cost me a few hours on this project.

Consistency and documentation are the only real _blockers_ (though they're more of annoyances). Other things are just unimplemented features: responsive suffixes and Harry's new heading idea.

### Concerns about a "dead" project

Beyond blockers, I still have concerns about using a "dead" project. At the moment, there do seem to be a lot of people interested in Inuit. That may change if Inuit stops being updated. Some people will switch to Aleut. Some people will go back to Bootstrap (or whatever is popular--I don't follow other frameworks very much). Some will develop their own personal ultra-customized forks.

I'm concerned that if I keep on using Inuit, I'll be on my own. If the project is "dead", it's hard for a community to form. People will assume nobody else is using it and keep to themselves. It will be up to me and me alone to notice potential problems and make changes. With no input from others, I would be limited to my own level of understanding.

Community is a huge part of any open source project. But it's hard for a community to thrive if the original project dies. With no central rallying point, fractures arise. I'm not sure Aleut would suit everyone. If it's opinionated, that means some people would need to change to match it. If _those_ people start their own fork, the community would be split--and become something less than if all parts were together.

I'm giving something of a worst case scenario, and I don't really _expect_ things to happen that way, but I think the fact stands that it would be boon to everyone if this original project grew and prospered.

The thing that really confuses me is the pull requests. It seems like the community really is interested in pitching in to help, but nobody is letting them. If documentation is missing, I'm sure a lot of people would be willing to step in. I would submit a few readme changes, if I though my PR had a chance of being merged.

But as it is, it looks like the project is completely frozen in this semi-done state, and that's when I start to get concerned. (I may be a little paranoiac from reading about _why a few too many times.)

Thank you for responding, and thank you again for helping support Inuit.

**Comment by anselmh** [comment]
Hey, thanks for the props but I really did not help creating inuit. My only role so far has been publishing the modules on npm. I’m sorry, as I do not know the status of this project as well, I cannot comment on any development, future here. And because of that reason, and because I have no authorization to work on my own on this project, I won’t do anything here, sorry. Still hoping for a status update from @csswizardry.

**Comment by robjwood** [comment]
I agree with @nenadjelovac and his point about it being perfectly good enough to use right now.

I admit that a lot of the time I got stuck I had to trawl Harry's blog for answers, along with @csshugs [Kitchen Sink](https://github.com/csshugs/inuit-kitchen-sink) for backup. So yes, I guess it could do with a little more documentation on the basics and getting it set up.

What I like about it is that if there are things you don't like or additional things you want it's very easy to amend what's there. You're not tied to any specific way of working.

**Comment by SevenZark** [comment]
I agree that the self-documenting code is not enough to dive in and start understanding how the framework works as a whole. Also, taking a look at csswizardy.com source as an example isn't particularly helpful to me since it's difficult to
a) Suss out what is custom and what is inuit, as it's all concatenated (which of course I would expect, so not a complaint)
b) Figure out which inuit rules correspond to which inuit modules.

For example, I see 'wrapper' class on that site that doesn't seem to exist anywhere inside inuit. I also see things that look like inuit, such as site-nav that I can't find anywhere in the new project. These things were actually easier to find and work with in the old repository, in my opinion.

Right now I'm trying to sell my current company on using inuit but it's a struggle and a big reason is the perceived stagnancy of development and the learning curve with no high-level documentation. "Just go and read the code" isn't always a great answer, especially not at the tip of the learning curve.

**Comment by maskedcoder** [comment]
@anselmh Whoa! It looks like things are happening now. For those who didn't notice, see
- https://github.com/inuitcss/generic.box-sizing/commit/9cc4ed0345ebe962935d90e51f3478680138dc93
- https://github.com/inuitcss/trumps.spacing/commit/458db86841aae88e1f2edd99721c3c18e7e0aa10
- https://github.com/inuitcss/generic.normalize/commit/a8f90f75632d6c02997e5a3318f9dafabc46a78c

That's pretty clearly progress, so I should probably close this issue (so as not to keep scaring people away). It would be nice though, if we got "official" word about the status of the project.

**Comment by anselmh** [comment]
@maskedcoder Hey, I think an “official” statement will come soon from Harry. Until then, I can say: Yes, there’s some progress in here again now and we will improve the framework drastically over the next months.

**Comment by inlikealion** [comment]
Super glad to see some movement!

**Comment by Boscop** [comment]
Any update on this? Would you recommend using inuitcss for new projects in 2018, instead of e.g. Bulma?

(I'm looking for a CSS-only framework (no JS).)

**Comment by csshugs** [comment]
@Boscop 
The stable major version 6.0.0 is released [here](https://github.com/inuitcss/inuitcss). You can totally use it for new projects.
